name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # The logic below handles the npm publication:
      - uses: actions/checkout@v5
        # ensure that a publication only occurs when a new release is created
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - uses: actions/setup-node@v5
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - run: bin/publish
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
